version: '3'
services:
  sugar:
    build: .
    ports:
      - "2999:2999"
    volumes:
      - node_modules:/node_app/node_modules
      - ./:/node_app
    environment:
      - SUGAR_REDIS_NO_TLS=true
      - SUGAR_TALK_USERNAME=sugar
      - SUGAR_TALK_PASSWORD=sugar
      - SUGAR_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis

volumes:
  node_modules: