// Generated by CoffeeScript 2.7.0
var MockPrimus;

MockPrimus = {
  connect: function() {
    return MockPrimus;
  },
  on: function() {
    return MockPrimus;
  },
  off: function() {
    return MockPrimus;
  },
  open: function() {
    return MockPrimus;
  },
  end: function() {
    return MockPrimus;
  },
  write: function() {
    return MockPrimus;
  }
};

module.exports = MockPrimus;
