// Generated by CoffeeScript 2.7.0
var auth;

auth = require('basic-auth');

module.exports = function(req, res, next) {
  var authed, credentials;
  credentials = auth(req);
  authed = credentials && credentials.name === process.env.SUGAR_TALK_USERNAME && credentials.pass === process.env.SUGAR_TALK_PASSWORD;
  if (authed) {
    return next();
  } else {
    res.writeHead(401, {
      'WWW-Authenticate': 'Basic realm=notifications.zooniverse.org"'
    });
    return res.end();
  }
};
