// Generated by CoffeeScript 2.7.0
var Events, RedisClient;

RedisClient = require('./redis_client');

Events = require('events');

Events.EventEmitter.defaultMaxListeners = 0;

class PubSub {
  constructor() {
    this.emitMessage = this.emitMessage.bind(this);
    this.subscribe = this.subscribe.bind(this);
    this.unsubscribe = this.unsubscribe.bind(this);
    this.publish = this.publish.bind(this);
    this.emitter = new Events.EventEmitter();
    this.redis = {
      pub: new RedisClient(),
      sub: new RedisClient()
    };
    this.redis.sub.on('message', this.emitMessage);
    this.redis.sub.on('pmessage', this.emitMessage);
  }

  emitMessage(pattern, channel, message) {
    return this.emitter.emit(pattern, JSON.parse(message || channel));
  }

  subscribe(pattern, fn) {
    var method;
    method = pattern.match(/\*|\[|\]|\?/) ? 'psubscribe' : 'subscribe';
    return this.redis.sub[`${method}Async`](pattern).then(() => {
      return this.emitter.on(pattern, fn);
    });
  }

  unsubscribe(pattern, fn) {
    var listeners, method;
    method = pattern.match(/\*|\[|\]|\?/) ? 'punsubscribe' : 'unsubscribe';
    this.emitter.removeListener(pattern, fn);
    listeners = this.emitter.listenerCount(pattern);
    if (listeners === 0) {
      return this.redis.sub[`${method}Async`](pattern);
    }
  }

  publish(channel, message) {
    return this.redis.pub.publishAsync(channel, JSON.stringify(message));
  }

};

module.exports = PubSub;
