// Generated by CoffeeScript 2.7.0
var Bluebird, Redis;

Bluebird = require('bluebird');

Redis = Bluebird.promisifyAll(require('redis'));

class RedisClient {
  constructor() {
    var auth, auth_opts, client, db, host, port;
    port = process.env.SUGAR_REDIS_PORT;
    port || (port = 6379);
    host = process.env.SUGAR_REDIS_HOST;
    host || (host = '127.0.0.1');
    auth = process.env.SUGAR_REDIS_AUTH;
    db = process.env.SUGAR_REDIS_DB || 1;
    // redis in test / dev doesn't have a TLS proxy in front of it
    auth_opts = process.env.SUGAR_REDIS_NO_TLS ? {} : {
      auth_pass: auth,
      tls: {
        servername: host
      }
    };
    client = Redis.createClient(port, host, auth_opts);
    client.select(db);
    return client;
  }

};

module.exports = RedisClient;
